config/routes.rb
Rails.application.routes.draw do
  get '/pages/index'
  get '/pages/about'
  get '/pages/contact'
  get '/pages/portfolio'  
  get '/pages/portfolioGames'
  get '/pages/portfolioVideo'
  get '/pages/portfolio3d'

  resources :posts
  root 'pages#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/ckeditor/asset.rb
class Ckeditor::Asset < ActiveRecord::Base
  include Ckeditor::Orm::ActiveRecord::AssetBase

  delegate :url, :current_path, :content_type, to: :data

  validates :data, presence: true
end

app/models/ckeditor/attachment_file.rb
class Ckeditor::AttachmentFile < Ckeditor::Asset
  mount_uploader :data, CkeditorAttachmentFileUploader, mount_on: :data_file_name

  def url_thumb
    @url_thumb ||= Ckeditor::Utils.filethumb(filename)
  end
end

app/models/ckeditor/picture.rb
class Ckeditor::Picture < Ckeditor::Asset
  mount_uploader :data, CkeditorPictureUploader, mount_on: :data_file_name

  def url_content
    url(:content)
  end
end

app/models/post.rb
class Post < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end

  def about
  end

  def Contact
  end

  def portfolio
  end

  def porfolio3d
  end

  def portfolioGames
  end

  def portfolioVideo
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :find_post, only: [:show, :edit, :update, :destroy]

  def index
    @post = Post.all
  end

  def show
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    if @post.save
      redirect_to @post, notice: "The new Post was created!"
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @post.update(post_params)
      redirect_to @post, notice: "Update was sucessfull"
    else
      render 'edit'
    end
  end

  def destroy
    @post.destroy
    redirect_to root_path, notice: "Post was deleted"
  end

  private

  def post_params
    params.require(:post).permit(:title, :body)
  end

  def find_post
    @post = Post.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/_footer.html.erb
<div class="footer">
	Copyright Whatever right?
</div>

app/views/layouts/_header.html.erb
 <div class="topnav">
 	<a href="index" >Home</a>
 	<div class="topnav-left">	 	 	
 		<a href="/pages/contact">contact</a>	 	
 		<a href="/pages/about">about</a>
 		<a href="#">Blog</a>	
 		<div class="dropdown">
 			<button class="dropbtn" onclick="myFunction()">Portfolio
 				<i class="fa fa-caret-down"></i>
 			</button>
 			<div class="dropdown-content" id="myDropdown">
 				<a href="/pages/portfolioVideo">Videos</a>
 				<a href="/pages/portfolioGames">Games</a>
 				<a href="/pages/portfolio3d">3D</a>
 			</div>
 		</div>
 	</div>
 </div> 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<title><%= yield(:title) %> | Ewerton Weishaupt Ruiz</title>
	<%= csrf_meta_tags %>
	<%= stylesheet_link_tag    'application', media: 'all'%>
	<%= javascript_include_tag 'application'%>
</head>

<body>
	<%= yield %>
</body>
</html>

app/views/pages/about.html.erb
<% provide(:title, "About") %>
<%= render 'layouts/header' %>
<html>
<body>
	<div class="header">
		<p class="header">About</p>
		<div class="divider"></div>				
			<div class="myimage">
				<img src="/images/me.jpg" width="250px"/>
			</div>		
		<div class="header-text">
			<span>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean pretium turpis ex, vel tincidunt magna interdum ut. Phasellus vitae sem ultricies, ullamcorper nulla ac, cursus elit. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Integer lectus est, malesuada et rhoncus et, interdum eget mi. Morbi ac ipsum sem. Nunc semper lobortis enim vitae euismod. Suspendisse varius mi ac dapibus placerat. Fusce quam lacus, sodales eu convallis et, cursus vitae ipsum. Nulla suscipit, mi quis egestas ultricies, magna quam iaculis nibh, consequat iaculis urna turpis et elit. Vivamus mattis volutpat dolor. Praesent vel ipsum iaculis, pretium dolor at, dictum lectus. Ut sed ipsum risus. Pellentesque dignissim, urna at ultrices malesuada, mauris mauris laoreet felis, sed sagittis ante velit vitae urna. Aliquam tristique est eget ipsum facilisis, non cursus sem efficitur. In hac habitasse platea dictumst.
			Ut rhoncus suscipit sapien non viverra. Nullam imperdiet diam a suscipit mollis. Quisque a maximus lectus. Aliquam fermentum quis ipsum ut ornare. Cras quis tempus eros. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Maecenas eu interdum augue. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Nulla sed vehicula augue. </span>				
			</div>	
			<div class="donwload-description">
				<p>Donwload resume</p>
				<a href="/images/Ewerton Weishaupt Ruiz CV.pdf" target="_blank" class="donwload-button">Donwload in PDF</a>
			</div>
			
			
		</div>

	</body>
	</html>

app/views/pages/contact.html.erb
<% provide(:title, "Contact") %>
<%= render 'layouts/header' %>
<html>
<body>
	<div class="header">
		<p class="header">Contact</p>
		<div class="divider"></div>
		<div class="header-text">
			<span><b>Email:</b> ewertonribeiroruiz@gmail.com</span><br>
			<span><b>Phone:</b> +45 28839234</span>		
			<div class="linkedin">
				<a href="https://www.linkedin.com/in/ewerton-ribeiro-weishaupt-ruiz-9323755/" target="blank"><img src="/images/linkedin.png" width="35px"></a>
			</div>
			</div>

			<p style="margin-top: 60px;">Send an email</p>		
			<div class="form-container">
			  <form action="https://formspree.io/shakamaiden@gmail.com" method="POST">
			    <label for="fname" style="color: white; font-size: 18px;"><b> Name</b></label>
			    <input type="text" id="fname" name="firstname" placeholder="Your name..">
			    <label for="subject" style="color: white; font-size: 18px;"><b>Message</b></label>
			    <textarea id="subject" name="subject" placeholder="Write something.." style="height:200px"></textarea>
			    <input type="submit" value="Submit">
			  </form>
					</div>
	</div>
</body>
</html>

app/views/pages/index.html.erb
<% provide(:title, "Home") %>
<%= render 'layouts/header' %>
<html>
<body>
	<div class="header">
		<p class="header">Recent Works</p>
		<div class="divider"></div>
		<!-- Beging Images -->		
		<div class="container">				
			<div class="img">				
				<img src="/images/nigthmare.jpeg" title="Project 1" class="image"/></a>
				<div class="overlay">	
				<a href="portfolio" class="overlay"></a>				
					<div class="text">
						<b>Hello World</b>
						<br>Whatever this project is description
					</div>
				</div>					
			</div>				
		</div>			
		<div class="container">	
			<div class="img">
				<img src="/images/football.jpeg" title="Project 2" class="image"/>
				<div class="overlay">
					<a href="portfolio" class="overlay"></a>
					<div class="text">
						<b>Hello World</b>
						<br>Whatever this project is description</div>
				</div>					
			</div>				
		</div>
		<div class="container">	
			<div class="img">
				<img src="/images/wii.jpeg" title="Project 2" class="image"/>
				<div class="overlay">
					<a href="portfolio" class="overlay"></a>
					<div class="text">						
						<b>Hello World</b>
						<br>Whatever this project is description</div>
				</div>					
			</div>
		</div>
			<div class="container">	
				<div class="img">
					<img src="/images/humvee.png" title="Project 2" class="image"/>
					<div class="overlay">
						<a href="portfolio" class="overlay"></a>
						<div class="text">
							<b>Hello World</b>
							<br>Whatever this project is description
						</div>
					</div>					
				</div>
			</div>
		</div>
		</div>
			<div class="container">	
				<div class="img">
					<img src="/images/violin.jpeg" title="Project 2" class="image"/>
					<div class="overlay">
						<a href="portfolio" class="overlay"></a>
						<div class="text">
							<b>Hello World</b>
							<br>Whatever this project is description
						</div>
					</div>					
				</div>
			</div>				
			<div class="container">	
				<div class="img">
					<img src="/images/shield.jpeg" title="Project 2" class="image"/>
					<div class="overlay">
						<a href="portfolio" class="overlay"></a>
						<div class="text">
							<b>Hello World</b>
							<br>Whatever this project is description
						</div>
					</div>					
				</div>
			</div>		
	</div>
	</body>
	</html>

app/views/pages/lightboxtest.html.erb
<!DOCTYPE html>
<html>
<body>
<div class="header">
    <p class="header">Portfolio</p>
    <div class="divider"></div>
<div class="row">
  <div class="column">
    <img src="img_nature.jpg" style="width:100%" onclick="openModal();currentSlide(1)" class="hover-shadow cursor">
  </div>
  <div class="column">
    <img src="img_fjords.jpg" style="width:100%" onclick="openModal();currentSlide(2)" class="hover-shadow cursor">
  </div>
  <div class="column">
    <img src="img_mountains.jpg" style="width:100%" onclick="openModal();currentSlide(3)" class="hover-shadow cursor">
  </div>
  <div class="column">
    <img src="img_lights.jpg" style="width:100%" onclick="openModal();currentSlide(4)" class="hover-shadow cursor">
  </div>
</div>

<div id="myModal" class="modal">
  <span class="close cursor" onclick="closeModal()">&times;</span>
  <div class="modal-content">

    <div class="mySlides">
      <div class="numbertext">1 / 4</div>
      <img src="img_nature_wide.jpg" style="width:100%">
    </div>

    <div class="mySlides">
      <div class="numbertext">2 / 4</div>
      <img src="img_fjords_wide.jpg" style="width:100%">
    </div>

    <div class="mySlides">
      <div class="numbertext">3 / 4</div>
      <img src="img_mountains_wide.jpg" style="width:100%">
    </div>
    
    <div class="mySlides">
      <div class="numbertext">4 / 4</div>
      <img src="img_lights_wide.jpg" style="width:100%">
    </div>
    
    <a class="prev" onclick="plusSlides(-1)">&#10094;</a>
    <a class="next" onclick="plusSlides(1)">&#10095;</a>

    <div class="caption-container">
      <p id="caption"></p>
    </div>


    <div class="column">
      <img class="demo cursor" src="img_nature_wide.jpg" style="width:100%" onclick="currentSlide(1)" alt="Nature and sunrise">
    </div>
    <div class="column">
      <img class="demo cursor" src="img_fjords_wide.jpg" style="width:100%" onclick="currentSlide(2)" alt="Trolltunga, Norway">
    </div>
    <div class="column">
      <img class="demo cursor" src="img_mountains_wide.jpg" style="width:100%" onclick="currentSlide(3)" alt="Mountains and fjords">
    </div>
    <div class="column">
      <img class="demo cursor" src="img_lights_wide.jpg" style="width:100%" onclick="currentSlide(4)" alt="Northern Lights">
    </div>
  </div>
</div>
</div>

<script src="javascripts/lightbox.js"> </script>
    
</body>
</html>

app/views/pages/portfolio.html.erb
<% provide(:title, "Portfolio") %>
<%= render 'layouts/header' %>
<!DOCTYPE html>
<html>
<body>
	<div class="header">
		<p class="header">3D</p>
		<div id="quad">
			<figure>
				<img src="/images/nigthmare.jpeg" alt="rose-red-wine">
				<figcaption>Rose Red Wine</figcaption>
			</figure>
			<figure>
				<img src="/images/football.jpeg" alt>
				<figcaption>Green Glass Bottle</figcaption>
			</figure>
			<figure>
				<img src="/images/humvee.png" alt>
				<figcaption>Guinness Barrels, Dublin</figcaption>
			</figure>
			<figure>
				<img src="/images/shield.jpeg" alt>
				<figcaption>Crystal Skull Vodka</figcaption>
			</figure>
			<figure>
				<img src="/images/violin.jpeg" alt>
				<figcaption>Crystal Skull Vodka</figcaption>
			</figure>
			<figure>
				<img src="/images/wii.jpeg"  alt>
				<figcaption>Guinness Barrels, Dublin</figcaption>
			</figure>
		</div>
	</div>
</body>
</html>

app/views/pages/portfolio3d.html.erb
<% provide(:title, "3D portfolio") %>
<%= render 'layouts/header' %>
<!DOCTYPE html>
<html>
<body>
	<div class="header">
		<p class="header">3D Works</p>
		<div id="quad">
			<figure>
				<img src="/images/nigthmare.jpeg" alt="rose-red-wine">
				<figcaption>Rose Red Wine</figcaption>
			</figure>
			<figure>
				<img src="/images/football.jpeg" alt>
				<figcaption>Green Glass Bottle</figcaption>
			</figure>
			<figure>
				<img src="/images/humvee.png" alt>
				<figcaption>Guinness Barrels, Dublin</figcaption>
			</figure>
			<figure>
				<img src="/images/shield.jpeg" alt>
				<figcaption>Crystal Skull Vodka</figcaption>
			</figure>
			<figure>
				<img src="/images/violin.jpeg" alt>
				<figcaption>Crystal Skull Vodka</figcaption>
			</figure>
			<figure>
				<img src="/images/wii.jpeg"  alt>
				<figcaption>Guinness Barrels, Dublin</figcaption>
			</figure>
		</div>
	</div>
</body>
</html>

app/views/pages/portfolioGames.html.erb
<% provide(:title, "Portolio Games") %>
<%= render 'layouts/header' %>
<!DOCTYPE html>
<html>
<body>
	<div class="header">
		<p class="header">Portfolio Games</p>
		<div id="quad">
			<figure>
				<img src="/images/nigthmare.jpeg" alt="rose-red-wine">
				<figcaption>Rose Red Wine</figcaption>
			</figure>
			<figure>
				<img src="/images/football.jpeg" alt>
				<figcaption>Green Glass Bottle</figcaption>
			</figure>
			<figure>
				<img src="/images/humvee.png" alt>
				<figcaption>Guinness Barrels, Dublin</figcaption>
			</figure>
			<figure>
				<img src="/images/shield.jpeg" alt>
				<figcaption>Crystal Skull Vodka</figcaption>
			</figure>
			<figure>
				<img src="/images/violin.jpeg" alt>
				<figcaption>Crystal Skull Vodka</figcaption>
			</figure>
			<figure>
				<img src="/images/wii.jpeg"  alt>
				<figcaption>Guinness Barrels, Dublin</figcaption>
			</figure>
		</div>
	</div>
</body>
</html>

app/views/pages/portfolioVideo.html.erb
<% provide(:title, "Video portfolio") %>
<%= render 'layouts/header' %>
<!DOCTYPE html>
<html>
<body>
	<div class="header">
		<p class="header">Portfolio Video</p>
		<div id="quad">
			<figure>
				<img src="/images/nigthmare.jpeg" alt="rose-red-wine">
				<figcaption>Rose Red Wine</figcaption>
			</figure>
			<figure>
				<img src="/images/football.jpeg" alt>
				<figcaption>Green Glass Bottle</figcaption>
			</figure>
			<figure>
				<img src="/images/humvee.png" alt>
				<figcaption>Guinness Barrels, Dublin</figcaption>
			</figure>
			<figure>
				<img src="/images/shield.jpeg" alt>
				<figcaption>Crystal Skull Vodka</figcaption>
			</figure>
			<figure>
				<img src="/images/violin.jpeg" alt>
				<figcaption>Crystal Skull Vodka</figcaption>
			</figure>
			<figure>
				<img src="/images/wii.jpeg"  alt>
				<figcaption>Guinness Barrels, Dublin</figcaption>
			</figure>
		</div>
	</div>
</body>
</html>

app/views/pages/testimages.html.erb
<% provide(:title, "Test Images") %>
<%= render 'layouts/header' %>
<!DOCTYPE html>
<html >
<head>
	<meta charset="UTF-8">
	<title>Quad Image Gallery</title>
</head>
<body>
	<div id="quad">
		<figure>
			<img src="/images/nigthmare.jpeg" alt="rose-red-wine">
			<figcaption>Rose Red Wine</figcaption>
		</figure>
		<figure>
			<img src="/images/football.jpeg" alt>
			<figcaption>Green Glass Bottle</figcaption>
		</figure>
		<figure>
			<img src="/images/humvee.png" alt>
			<figcaption>Guinness Barrels, Dublin</figcaption>
		</figure>
		<figure>
			<img src="/images/shield.jpeg" alt>
			<figcaption>Crystal Skull Vodka</figcaption>
		</figure>
		<figure>
			<img src="/images/violin.jpeg" alt>
			<figcaption>Crystal Skull Vodka</figcaption>
		</figure>
		<figure>
			<img src="/images/wii.jpeg"  alt>
			<figcaption>Guinness Barrels, Dublin</figcaption>
		</figure>
	</div>
</body>
</html>

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
	<%= render 'shared/error_messages' %>

	<%= f.label :title %>
	<%= f.text_field :title, placeholder: "Type the title of the post" %><br>
	<%= f.label :body %>
	<%= f.text_area :body, size: "60x12", placeholder: "Type the content of the post" %><br>
	<%= f.submit %>
<% end %>

//Stoped here in the form

app/views/posts/edit.html.erb
<h1>Edit Post</h1>
<%= render "form" %>
<%= link_to "Back", root_path %>

app/views/posts/index.html.erb
<% posts.each do |post| %>
  <h1><%= link_to "post.title", post%></h1>
  <p><%= post.content %></p>
<% end %>

app/views/posts/new.html.erb
<h1>New Post</h1>
<%= render 'form' %>
<%= link_to "Back", root_path %>

app/views/posts/show.html.erb
<h1><%= @post.title %></h1>
<p><%= post.content %></p>
<%= link_to "Edit", edit_post_path(@post) %>
<%= link_to "Delete", @post, method: :delete, :data { confirm: "Are you sure you want do delete the post?"} %>